ish_manager-master/config/routes.rb
IshManager::Engine.routes.draw do
  root :to => 'application#home'

  resources :campaigns

  resources :cities do
    resources :features
    resources :newsitems
    resources :reports
    resources :galleries
    resources :users
    resources :videos
    resources :events
    resources :venues
    resources :tags
  end

  resources :email_templates
  resources :events

  resources :feature
  resources :friends

  get 'galleries',              :to => 'galleries#index'
  get 'galleries/index_titles', :to => 'galleries#index', :defaults => { :render_type => Gallery::RENDER_TITLES }
  get 'galleries/index_thumbs', :to => 'galleries#index', :defaults => { :render_type => Gallery::RENDER_THUMBS }
  resources :galleries do
    post 'multiadd', :to => 'photos#j_create', :as => :multiadd
    resources :newsitems
  end

  resources :invoices do
    # resources :payments
  end

  get 'leads',      :to => 'leads#index', :defaults => { :is_done => false }
  get 'leads/done', :to => 'leads#index', :defaults => { :is_done => true }, :as => :done_leads
  resources :leads

  resources :newsitems

  resources :orders
  get 'co_tailors',                :to => 'co_tailors#home'
  post 'co_tailors/products',      :to => 'co_tailors#create_product'
  patch 'co_tailors/products/:id', :to => 'co_tailors#update_product', :as => :co_tailors_product

  resources :photos
  resources :payments
  ## profiles, see user_profiles
  
  resources :reports

  resources :sites do
    resources :features
    resources :newsitems

    get 'reports', :to => 'sites#reports'
    resources :reports

    get 'galleries', :to => 'sites#galleries'

    resources :galleries
    resources :videos
    resources :tags
  end
  
  resources :stock_actions
  resources :stock_options
  resources :stock_watches

  resources :tags do
    resources :features
    resources :newsitems

    resources :reports
    resources :galleries
    resources :videos
  end

  resources :user_profiles do
    resources :newsitems
  end
  resources :user_profiles, :as => :profiles do
    resources :newsitems
  end

  resources :venues
  resources :videos
  
end

ish_manager-master/app/controllers/ish_manager/ally_controller.rb
class IshManager::AllyController < IshManager::ApplicationController

  def home
    authorize! :ally_home, IshManager::Ability
  end

end

ish_manager-master/app/controllers/ish_manager/application_controller.rb
module IshManager
  class ApplicationController < ActionController::Base
    # protect_from_forgery :with => :exception, :prepend => true
    before_action :set_current_ability
    before_action :set_changelog
    check_authorization
    rescue_from ::CanCan::AccessDenied, :with => :access_denied

    def home
      authorize! :home, IshManager::Ability
      render 'home'
    end

    #
    # private
    #
    private

    def set_changelog
      @version = Gem.loaded_specs['ish_manager'].version.to_s
    end

    def set_current_ability
      @current_ability ||= ::IshManager::Ability.new( current_user )
    end

    def set_lists
      @sites_list = Site.all.list
      @cities_list = City.all.list
      @venues_list = Venue.all.list
      @reports_list = Report.all.list
      @galleries_list = Gallery.all.list
      @videos_list = Video.all.list
      @user_profiles_list = IshModels::UserProfile.all.list
      @tags_list = Tag.list
    end

    def access_denied exception
      store_location_for :user, request.path
      redirect_to user_signed_in? ? root_path : Rails.application.routes.url_helpers.new_user_session_path, :alert => exception.message
    end

    def pp_errors err
      err
    end

    def puts! a, b=''
      puts "+++ +++ #{b}"
      puts a.inspect
    end

    def update_profile_pic
      return unless params[:photo]
      @photo = Photo.new :photo => params[:photo]
      @photo.user_profile = @current_user.profile
      flag = @photo.save
      @resource.profile_photo = @photo
      flagg = @resource.save
      if flag && flagg
        flash[:notice] = 'Success'
      else
        flash[:alert] = "No Luck. #{@photo.errors.messages} #{@resource.errors.messages}"
      end
      # redirect_to resource_path( @resource )
    end
    
    def resource_path resource
      case resource.class.name
      when 'City'
        city_path( resource.id )
      when 'Event'
        event_path( resource.id )
      when 'Venue'
        venue_path( resource.id )
      end
    end

  end
end

ish_manager-master/app/controllers/ish_manager/campaigns_controller.rb
class IshManager::CampaignsController < IshManager::ApplicationController

  def index
    authorize! :index, Ish::Campaign
    @campaigns = Ish::Campaign.where( :profile => current_user.profile, :is_trash => false )
    if params[:is_done]
      @campaigns = @campaigns.where( :is_done => true )
    else
      @campaigns = @campaigns.where( :is_done => false )
    end
  end

  def new
    @new_campaign = Ish::Campaign.new
    authorize! :new, @new_campaign
  end

  def create
    @campaign = Ish::Campaign.new params[:campaign].permit!
    @campaign.profile = current_user.profile
    authorize! :create, @campaign
    if @campaign.save
      flash[:notice] = "created campaign"
    else
      flash[:alert] = "Cannot create campaign: #{@campaign.errors.messages}"
    end
    redirect_to :action => 'index'
  end

  def show
    authorize! :redirect, IshManager::Ability
    redirect_to :action => :edit, :id => params[:id]
  end

  def edit
    @campaign = Ish::Campaign.find params[:id]
    authorize! :edit, @campaign
  end

  def update
    @campaign = Ish::Campaign.find params[:id]
    authorize! :update, @campaign
    if @campaign.update_attributes params[:campaign].permit!
      flash[:notice] = 'Successfully updated campaign.'
    else
      flash[:alert] = "Cannot update campaign: #{@campaign.errors.messages}"
    end
    redirect_to :action => 'index'
  end

end

ish_manager-master/app/controllers/ish_manager/cities_controller.rb
class IshManager::CitiesController < IshManager::ApplicationController
  before_action :set_lists, :only => [ :new_newsitem, :create_newsitem ]
  before_action :sett_city, :only => [ :show, :edit ]

  def index
    authorize! :cities_index, Manager
    @cities = City.all
    @city = City.new
    @photo = Photo.new
  end
  
  def show
    authorize! :show, @city
    @videos = @city.videos.page( params[:videos_page] ).per( 10 )
  end
  
  def new
    @city = City.new
    authorize! :new, City

    @photo = Photo.new
  end

  def create
    @city = City.new params[:city].permit!
    authorize! :create, @city

    if @city.save
      flash[:notice] = 'Success'
      redirect_to cities_path
    else
      flash[:alert] = 'No Luck'
      render :action => :new
    end
  end

  def edit
    authorize! :edit, @city
  end
  
  def update
    @city = City.find( params[:id] )
    authorize! :update, @city
    @city.update_attributes params[:city].permit!
    if params[:photo]
      photo = Photo.new :photo => params[:photo]
      @city.profile_photo = photo
    end
    if @city.save
      ::IshModels::CacheKey.one.update_attributes( :cities => Time.now, :feature_cities => Time.now )
      flash[:notice] = 'Success'
      redirect_to edit_city_path @city.id
    else
      flash[:alert] = 'No Luck. ' + @city.errors.inspect
      @newsitems = @city.newsitems.all.page( params[:newsitems_page] )
      @features = @city.features.all.page( params[:features_page] )
      @photo = Photo.new
      render :action => :edit
    end
  end

  def change_profile_pic
    authorize! :change_profile_pic, City
    @city = City.find params[:id]
    @photo = Photo.new params[:photo]
    @photo.user = @current_user
    flag = @photo.save
    @city.profile_photo = @photo
    flagg = @city.save
    if flag && flagg
      flash[:notice] = 'Success'
    else
      flash[:alert] = "No Luck. #{@photo.errors.messages} #{@city.errors.messages}"
    end
    redirect_to cities_path
  end

  private

  def sett_city
    @city = City.find params[:id]
    @photo = Photo.new
  end

  def set_lists
    @list_reports = Report.all.list
    @list_galleries = Gallery.all.list
    @list_users = [['', nil]] + User.all.order_by( :name => :asc ).map { |u| [u.username, u.username] }
  end

end

ish_manager-master/app/controllers/ish_manager/co_tailors_controller.rb
class IshManager::CoTailorsController < IshManager::ApplicationController

  def home
    authorize! :home, ::CoTailors
    @products = ::CoTailors::Product.all
  end

  def create_product
    authorize! :create, ::CoTailors::Product
    @product = ::CoTailors::Product.new params[:co_tailors_product].permit!
    if @product.save
      flash[:notice] = 'Created product'
    else
      flash[:alert] = 'Cannot create product: ', @product.errors.messages.to_s
    end
    redirect_to :action => 'home'
  end

  def update_product
    @product = ::CoTailors::Product.find params[:id]
    authorize! :update, @product
    if @product.update_attributes params[:co_tailors_product].permit!
      flash[:notice] = 'updated product'
    else
      flash[:alert] = 'Cannot update product: ', @product.errors.messages.to_s
    end
    redirect_to :action => 'home'
  end


end

ish_manager-master/app/controllers/ish_manager/events_controller.rb
class IshManager::EventsController < IshManager::ApplicationController

  before_action :set_lists

  def index
    authorize! :index, ::Event
    @events = Event.all
    if params[:city_id]
      @resource = City.find( params[:city_id] )
      @events = @resource.events
    end
  end

  def new
    @event = Event.new
    authorize! :new, @event
  end

  def create
    @event = Event.new params[:event].permit!
    authorize! :create, @event
    if @event.save
      @event.city.touch
      redirect_to :action => :index
    else
      flash[:alert] = @event.errors.messages
      render :action => :new
    end
  end

  def edit
    @event = Event.find params[:id]
    authorize! :edit, @event
  end

  def update
    @event = Event.find params[:id]
    authorize! :update, @event

    if params[:photo]
      photo = Photo.new :photo => params[:photo]
      @event.profile_photo = photo
    end

    flag = @event.update_attributes params[:event].permit!
    if flag
      @event.city.touch
      flash[:notice] = 'updated event'
      redirect_to :action => :index
    else
      flash[:alert] = "No luck: #{@event.errors.messages}"
      render :action => :edit
    end
  end

  def show
    @event = Event.find params[:id]
    authorize! :show, @event
    redirect_to :action => :edit, :id => @event.id
  end

end

ish_manager-master/app/controllers/ish_manager/features_controller.rb
class IshManager::FeaturesController < IshManager::ApplicationController

  before_action :set_lists
  
  def new
    if params[:city_id]
      @city = City.find params[:city_id]
      authorize! :new_feature, @city
    elsif params[:site_id]
      @site = Site.find params[:site_id]
      authorize! :new_feature, @site
    elsif params[:tag_id]
      @tag = Tag.find params[:tag_id]
      authorize! :new_feature, @tag
    end

    @feature = Feature.new
  end

  def create
    @feature = Feature.new params[:feature].permit!

    if params[:city_id]
      @city = City.find params[:city_id]
      authorize! :create_feature, @city
      @city.features << @feature
      @city.touch
      redirect_path = cities_path
    end
    if params[:site_id]
      @site = Site.find params[:site_id]
      authorize! :create_feature, @site
      @site.features << @feature
      @site.touch
      redirect_path = sites_path
    end
    if params[:tag_id]
      @tag = Tag.find params[:tag_id]
      authorize! :create_feature, @tag
      @tag.features << @feature
      @tag.touch
      redirect_path = tags_path
    end

    if (@city && @city.save) || (@site && @site.save) || (@tag && @tag.save)
      flash[:notice] = 'Success.'
      redirect_to redirect_path
    else
      flash[:alert] = "No luck: #{pp_errors @feature.errors.messages}"
      render :action => :new
    end
  end

  def edit
    if params[:city_id]
      @city = City.find params[:city_id]
      @feature = @city.features.find params[:id]
      authorize! :edit_feature, @city
    end

    if params[:site_id]
      @site = Site.find params[:site_id]
      @feature = @site.features.find params[:id]
      authorize! :edit_feature, @site
    end

    if params[:tag_id]
      @tag = Tag.find params[:tag_id]
      @feature = @tag.features.find params[:id]
      authorize! :edit_feature, @tag
    end
   
    if params[:venue_id]
      @venue = Tag.find params[:venue_id]
      @feature = @venue.features.find params[:id]
      authorize! :edit_feature, @venue
    end

  end

  def update
    unless params[:city_id].blank?
      @city = City.find params[:city_id] 
      authorize! :update_feature, @city
      @feature = @city.features.find params[:id]
      redirect_path = city_path( @city )
    end
    unless params[:site_id].blank?
      @site = Site.find params[:site_id] 
      authorize! :update_feature, @site
      @feature = @site.features.find params[:id]
      redirect_path = site_path( @site )
    end
    unless params[:tag_id].blank?
      @tag = Tag.find params[:tag_id]
      authorize! :update_feature, @tag
      @feature = @tag.features.find params[:id]
      redirect_path = tag_path( @tag )
    end
    
    authorize! :update, @feature

    if @feature.update_attributes params[:feature].permit!
      @city.touch if @city
      @site.touch if @site
      @tag.touch  if @tag

      flash[:notice] = 'updated feature'
      redirect_to redirect_path
    else
      flash[:alert] = 'No Luck. ' + @feature.errors.messages
      render :action => :edit
    end    
  end

  def index
    if params[:tag_id]
      @resource = Tag.find params[:tag_id]
    end
    if params[:site_id]
      @resource = Site.find params[:site_id]
    end
    authorize! :features_index, @resource
    @features = @resource.features
  end

  def destroy
    if params[:tag_id]
      @resource = Tag.find params[:tag_id]
    elsif params[:city_id]
      @resource = City.find params[:city_id]
    elsif params[:site_id]
      @resource = Site.find params[:site_id]
    end
    authorize! :destroy_feature, @resource
    @feature = @resource.features.find params[:id]
    authorize! :destroy, @feature

    if @feature.destroy
      @resource.touch
      flash[:notice] = 'Success.'
    else
      flash[:alert] = "No luck. " + @feature.errors.messages
    end
    redirect_to request.referrer
  end
  
end

ish_manager-master/app/controllers/ish_manager/friends_controller.rb
class IshManager::FriendsController < IshManager::ApplicationController

  def index
    authorize! :friends_index, IshModels::UserProfile
    @new_friend = IshModels::UserProfile.new

    @friends = current_user.profile.friends
    friend_ids = @friends.map &:id
  end

  def create
    @friend = ::IshModels::UserProfile.find_by( :email => params[:friend][:email] ) # .includes( :shared_galleries )

    authorize! :friends_new, @friend

    me = current_user.profile
    me.friends << @friend
    if me.save
      flash[:notice] = 'Added Friend'
    else
      flash[:alert] = "Cannot add friend: #{me.errors.messages}"
    end
    redirect_to :action => 'index'
  end

end

ish_manager-master/app/controllers/ish_manager/invoices_controller.rb
class IshManager::InvoicesController < IshManager::ApplicationController

  before_action :set_lists

  def index
    authorize! :index, Ish::Invoice
    @invoices = Ish::Invoice.all.includes( :payments )
  end

  def new
    authorize! :new, @invoice
  end

  def create
    @invoice = Ish::Invoice.new params[:invoice].permit!
    authorize! :create, @invoice
    if @invoice.save
      flash[:notice] = "created invoice"
    else
      flash[:alert] = "Cannot create invoice: #{@invoice.errors.messages}"
    end
    redirect_to :action => 'index'
  end

  def update
    @invoice = Ish::Invoice.find params[:id]
    authorize! :update, @invoice
    if @invoice.update_attributes params[:invoice].permit!
      flash[:notice] = 'Success'
      redirect_to :action => 'index'
    else
      flash[:alert] = "Cannot update invoice: #{@invoice.errors.messages}"
    end
    redirect_to :action => 'index'
  end

  #
  # private
  #
  private
  
  def set_lists
    @invoice_number = Ish::Invoice.order_by( :number => :desc ).first
    @invoice_number = @invoice_number ? @invoice_number.number + 1 : 1
    @new_invoice = Ish::Invoice.new :number => @invoice_number
  end

end

ish_manager-master/app/controllers/ish_manager/leads_controller.rb
class IshManager::LeadsController < IshManager::ApplicationController

  def index
    authorize! :index, Ish::Lead
    @leads = Ish::Lead.where( :profile => current_user.profile, :is_trash => false )
    if params[:is_done]
      @leads = @leads.where( :is_done => true )
    else
      @leads = @leads.where( :is_done => false )
    end
    render :layout => 'ish_manager/application_no_materialize'
  end

  def new
    @new_lead = Ish::Lead.new
    authorize! :new, @new_lead
  end

  def create
    @lead = Ish::Lead.new params[:lead].permit!
    @lead.profile = current_user.profile
    authorize! :create, @lead
    if @lead.save
      flash[:notice] = "created lead"
    else
      flash[:alert] = "Cannot create lead: #{@lead.errors.messages}"
    end
    redirect_to :action => 'index'
  end

  def show
    authorize! :redirect, IshManager::Ability
    redirect_to :action => :edit, :id => params[:id]
  end

  def edit
    @lead = Ish::Lead.find params[:id]
    authorize! :edit, @lead
  end

  def update
    @lead = Ish::Lead.find params[:id]
    authorize! :update, @lead
    if @lead.update_attributes params[:lead].permit!
      flash[:notice] = 'Successfully updated lead.'
    else
      flash[:alert] = "Cannot update lead: #{@lead.errors.messages}"
    end
    redirect_to :action => 'index'
  end

end

ish_manager-master/app/views/ish_manager/application/_form_errors.haml
- if item.errors.any?
  .error-explanation
    %h5= t('e.there_are_errors')
    %ul
      - item.errors.full_messages.each do |msg|
        %li= msg

ish_manager-master/app/views/ish_manager/application/_main_footer.haml
.manager--main-footer
  .container
    .row
      %i.fa.fa-compress.collapse-expand#collapseFooter
      .content
        .col-sm-5
          - if defined?( current_user ) && current_user
            %ul
              %li >[ #{current_user.email} ]<
              %li >[ #{current_user.profile.role_name} ]<
          - else
            Please log in
            = link_to '[+]', main_app.new_user_session_path

        .col-sm-5
          %br
          \~__^
          = @version
          -# <pre>#{@changelog}</pre>
          %br
          %br
          %br
          %br
          %br
        .col-sm.2
          = button_to 'Logout', main_app.destroy_user_session_path, :method => :delete

ish_manager-master/app/views/ish_manager/application/_main_header.haml
.manager--main-header
  .container
    .row
      .col-sm-12
        %i.fa.fa-compress.collapse-expand#collapseHeader
        .content
          %ul.nav.nav-pills
            %li{ :class => params[:controller] == 'ish_manager/galleries'     ? 'active' : '' }= link_to 'Galleries', galleries_path
            %li{ :class => params[:controller] == 'ish_manager/reports'       ? 'active' : '' }= link_to 'Reports',   reports_path
            %li{ :class => params[:controller] == 'ish_manager/videos'        ? 'active' : '' }= link_to 'Videos',    videos_path
            %li{ :class => params[:controller] == 'ish_manager/friends      ' ? 'active' : '' }= link_to 'Friends',   friends_path          
          %ul.nav.nav-pills
  %hr

ish_manager-master/app/views/ish_manager/application/_main_header_.haml
.manager--main-header
  .container
    .row
      .col-sm-12
        %i.fa.fa-compress.collapse-expand#collapseHeader
        .content
          %ul.nav.nav-pills
            %li{ :class => params[:controller] == 'ish_manager/galleries'     ? 'active' : '' }= link_to 'Galleries', galleries_path
            %li{ :class => params[:controller] == 'ish_manager/reports'       ? 'active' : '' }= link_to 'Reports',   reports_path
            %li{ :class => params[:controller] == 'ish_manager/videos'        ? 'active' : '' }= link_to 'Videos',    videos_path
            %li{ :class => params[:controller] == 'ish_manager/friends      ' ? 'active' : '' }= link_to 'Friends',   friends_path          
          %ul.nav.nav-pills
  %hr

ish_manager-master/app/views/ish_manager/application/_main_header_admin.haml
.manager--main-header
  .container
    .row
      .col-sm-12
        %i.fa.fa-compress.collapse-expand#collapseHeader
        .content
          %ul.nav.nav-pills
            %li{ :class => params[:controller] == 'ish_manager/cities'        ? 'active' : '' }= link_to 'Cities',    cities_path
            %li{ :class => params[:controller] == 'ish_manager/events'        ? 'active' : '' }= link_to 'Events',    events_path
            %li{ :class => params[:controller] == 'ish_manager/venues'        ? 'active' : '' }= link_to 'Venues',    venues_path
            %li{ :class => params[:controller] == 'ish_manager/user_profiles' ? 'active' : '' }= link_to 'Profiles',  user_profiles_path
            %li{ :class => params[:controller] == 'ish_manager/friends      ' ? 'active' : '' }= link_to 'Friends',   friends_path

          %ul.nav.nav-pills          
            %li{ :class => params[:controller] == 'ish_manager/sites'         ? 'active' : '' }= link_to 'Sites',     sites_path
            %li{ :class => params[:controller] == 'ish_manager/galleries'     ? 'active' : '' }= link_to 'Galleries', galleries_path
            %li{ :class => params[:controller] == 'ish_manager/reports'       ? 'active' : '' }= link_to 'Reports',   reports_path
            %li{ :class => params[:controller] == 'ish_manager/videos'        ? 'active' : '' }= link_to 'Videos',    videos_path
            %li{ :class => params[:controller] == 'ish_manager/tags'          ? 'active' : '' }= link_to 'Tags',      tags_path

          %ul.nav.nav-pills
            %li{ class: params[:controller] == 'ish_manager/newsitems' ? 'active' : '' }= link_to '+Newsitem', new_newsitem_path

          %ul.nav.nav-pills
            -# %li{ :class => params[:controller] == 'ish_manager/ally'          ? 'active' : '' }= link_to 'Ally',      ally_root_path
            %li{ :class => params[:controller] == 'ish_manager/stock_actions' ? 'active' : '' }= link_to 'Stock Actions', stock_actions_path
            %li{ :class => params[:controller] == 'ish_manager/stock_options' ? 'active' : '' }= link_to 'Stock Options', stock_options_path
            %li{ :class => params[:controller] == 'ish_manager/stock_watches' ? 'active' : '' }= link_to 'Stock Watches', stock_watches_path

          %ul.nav.nav-pills
            %li{ :class => params[:controller] == 'ish_manager/invoices'      ? 'active' : '' }= link_to 'Invoices', invoices_path
            %li{ :class => params[:controller] == 'ish_manager/payments'      ? 'active' : '' }= link_to 'Payments', payments_path

          %ul.nav.nav-pills
            %li{ :class => params[:controller] == 'ish_manager/leads'         ? 'active' : '' }= link_to 'Leads', leads_path
            %li{ :class => params[:controller] == 'ish_manager/campaigns'     ? 'active' : '' }= link_to 'Campaigns', campaigns_path

          %ul.nav.nav-pills
            %li{ :class => params[:controller] == 'ish_manager/orders'        ? 'active' : '' }= link_to 'Orders', orders_path
            %li{ :class => params[:controller] == 'ish_manager/co_tailors'    ? 'active' : '' }= link_to 'Co Tailors', co_tailors_path
  %hr

ish_manager-master/app/views/ish_manager/application/_main_header_guy.haml
.manager--main-header
  .container
    .row
      .col-sm-12
        %i.fa.fa-compress.collapse-expand#collapseHeader
        .content
          %ul.nav.nav-pills
            %li{ :class => params[:controller] == 'ish_manager/galleries'     ? 'active' : '' }= link_to 'Galleries', galleries_path
            %li{ :class => params[:controller] == 'ish_manager/reports'       ? 'active' : '' }= link_to 'Reports',   reports_path
            %li{ :class => params[:controller] == 'ish_manager/videos'        ? 'active' : '' }= link_to 'Videos',    videos_path
            %li{ :class => params[:controller] == 'ish_manager/friends      ' ? 'active' : '' }= link_to 'Friends',   friends_path          
          %ul.nav.nav-pills
  %hr

ish_manager-master/app/views/ish_manager/application/_meta.haml
.meta
  <b>On</b> #{item.created_at.to_s[0...10]}
  - if item.city
    <b>In City:</b> #{link_to item.city.name, city_path( item.city )}
  - if item.tag
    <b>Tag:</b> #{link_to item.tag.name, tag_path( item.tag )}
  - if item.site
    <b>Site:</b>
    = link_to "#{item.site.domain}/#{item.site.lang}", site_path( item.site )
  - if item.respond_to?( :venue ) && item.venue
    <b>Venue:</b>
    = link_to item.venue.name, venue_path( item.venue )
  - if item.user_profile
    <b>By UserProfile:</b>
    = link_to item.user_profile.name, edit_user_profile_path( item.user_profile )
    

ish_manager-master/app/views/ish_manager/application/_profile_pic.haml
.change-profile-pic
  %label Change profile pic
  = file_field_tag :photo
  - begin
    = image_tag resource.profile_photo.photo.url(:thumb)
    - rescue

ish_manager-master/app/views/ish_manager/application/home.haml
Welcome home! Your role is #{current_user.profile.role_name}.