ish_manager-master/config/routes.rb
IshManager::Engine.routes.draw do
  root :to => 'application#home'

  resources :campaigns

  resources :cities do
    resources :features
    resources :newsitems
    resources :reports
    resources :galleries
    resources :users
    resources :videos
    resources :events
    resources :venues
    resources :tags
  end

  resources :email_templates
  resources :events

  resources :feature
  resources :friends

  get 'galleries',              :to => 'galleries#index'
  get 'galleries/index_titles', :to => 'galleries#index', :defaults => { :render_type => Gallery::RENDER_TITLES }
  get 'galleries/index_thumbs', :to => 'galleries#index', :defaults => { :render_type => Gallery::RENDER_THUMBS }
  resources :galleries do
    post 'multiadd', :to => 'photos#j_create', :as => :multiadd
    resources :newsitems
  end

  resources :invoices do
    # resources :payments
  end

  get 'leads',      :to => 'leads#index', :defaults => { :is_done => false }
  get 'leads/done', :to => 'leads#index', :defaults => { :is_done => true }, :as => :done_leads
  resources :leads

  resources :newsitems

  resources :orders
  get 'co_tailors',                :to => 'co_tailors#home'
  post 'co_tailors/products',      :to => 'co_tailors#create_product'
  patch 'co_tailors/products/:id', :to => 'co_tailors#update_product', :as => :co_tailors_product

  resources :photos
  resources :payments
  ## profiles, see user_profiles
  
  resources :reports

  resources :sites do
    resources :features
    resources :newsitems

    get 'reports', :to => 'sites#reports'
    resources :reports

    get 'galleries', :to => 'sites#galleries'

    resources :galleries
    resources :videos
    resources :tags
  end
  
  resources :stock_actions
  resources :stock_options
  resources :stock_watches

  resources :tags do
    resources :features
    resources :newsitems

    resources :reports
    resources :galleries
    resources :videos
  end

  resources :user_profiles do
    resources :newsitems
  end
  resources :user_profiles, :as => :profiles do
    resources :newsitems
  end

  resources :venues
  resources :videos
  
end

ish_manager-master/app/controllers/ish_manager/galleries_controller.rb
class IshManager::GalleriesController < IshManager::ApplicationController

  before_action :set_lists
  
  def index
    authorize! :index, Gallery
    @galleries = Gallery.unscoped.where( :is_trash => false, :user_profile => current_user.profile
                                       ).order_by( :created_at => :desc )

    if params[:render_type] == Gallery::RENDER_TITLES
      render 'index_titles'
      return
    else
      if params[:q]
        @galleries = @galleries.where({ :name => /#{params[:q]}/i })      
      end
      @galleries = @galleries.page( params[:galleries_page] ).per( 20 )
      @shared_galleries = current_user.profile.shared_galleries.unscoped.where( :is_trash => false ).page( params[:shared_galleries_page] ).per( 10 )
    end

  end

=begin
  def index_title
  end
  def index_thumb
    @galleries = Gallery.unscoped.where( :is_trash => false 
                                       ).order_by( :created_at => :desc 
                                                 ).page( params[:galleries_page] ).per( 10 )
  end
  def index_mini
    @galleries = Gallery.unscoped.where( :is_trash => false 
                                       ).order_by( :created_at => :desc 
                                                 ).page( params[:galleries_page] ).per( 10 )
  end
=end

  def new
    @gallery = Gallery.new
    authorize! :new, @gallery
    @cities_list = City.list
    @tags_list = Tag.list
  end

  def create
    params[:gallery][:shared_profiles] ||= []
    params[:gallery][:shared_profiles].delete('')
    params[:gallery][:shared_profiles] = IshModels::UserProfile.find params[:gallery][:shared_profiles]
    @gallery = Gallery.new params[:gallery].permit!
    @gallery.user_profile = current_user.profile
    @gallery.username = current_user.profile.username
    authorize! :create, @gallery

    if @gallery.save
      ::IshManager::ApplicationMailer.shared_galleries( params[:gallery][:shared_profiles], @gallery ).deliver
      flash[:notice] = 'Success'
      redirect_to galleries_path
    else
      puts! @gallery.errors.messages
      flash[:alert] = 'No Luck. ' + @gallery.errors.inspect
      @cities_list = City.list
      @tags_list = Tag.list
      render :action => 'new'
    end
  end

  def edit
    @gallery = Gallery.unscoped.find params[:id]
    authorize! :edit, @gallery
  end

  def update
    @gallery = Gallery.unscoped.find params[:id]
    old_shared_profile_ids = @gallery.shared_profiles.map(&:id)
    authorize! :update, @gallery

    params[:gallery][:shared_profiles].delete('')
    # params[:gallery][:shared_profiles] = IshModels::UserProfile.find( params[:gallery][:shared_profiles] ).to_a
    params[:gallery][:shared_profile_ids] = params[:gallery][:shared_profiles]
    params[:gallery].delete :shared_profiles

    # puts! params[:gallery][:shared_profiles], 'shared profiles'
    if @gallery.update_attributes( params[:gallery].permit! )
      new_shared_profiles = IshModels::UserProfile.find( params[:gallery][:shared_profile_ids] 
                                                       ).select do |p|
        !old_shared_profile_ids.include?( p.id )
      end
      ::IshManager::ApplicationMailer.shared_galleries( new_shared_profiles, @gallery ).deliver
      flash[:notice] = 'Success.'
      redirect_to galleries_path
    else
      puts! @gallery.errors.messages, 'cannot save gallery'
      flash[:alert] = 'No Luck. ' + @gallery.errors.messages.to_s
      render :action => :edit
    end
  end                           

  def show
    begin
      @gallery = Gallery.unscoped.find_by :galleryname => params[:id]
    rescue
      @gallery = Gallery.unscoped.find params[:id]
    end
    authorize! :show, @gallery
    @photos = @gallery.photos.unscoped.where({ :is_trash => false })
    @deleted_photos = @gallery.photos.unscoped.where({ :is_trash => true })
  end

  def destroy
    @gallery = Gallery.unscoped.find params[:id]
    authorize! :destroy, @gallery
    @gallery.is_trash = true
    @gallery.save
    flash[:notice] = 'Logically deleted gallery.'
    redirect_to galleries_path
  end

  def j_show
    @gallery = Gallery.unscoped.find( params[:id] )
    authorize! :show, @gallery
    respond_to do |format|
      format.json do
        jjj = {}
        jjj[:photos] = @gallery.photos.map do |ph|
          { :thumbnail_url => ph.photo.url( :thumb ),
          :delete_type => 'DELETE',
          :delete_url => photo_path(ph) }
        end
        render :json => jjj
      end
    end
  end

end

ish_manager-master/app/views/ish_manager/galleries/trash/_index.haml
_list.haml

ish_manager-master/app/views/ish_manager/galleries/trash/_list_short.haml
%ul
  - galleries.each do |gallery|
    %li
      = link_to '[~]', edit_gallery_path( gallery )
      = link_to gallery.name, gallery_path( gallery )
      %br
      \&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      N photos: #{gallery.photos.length}

ish_manager-master/app/views/ish_manager/galleries/trash/_menu_secondary.haml
.row.menu-secondary
  .large-12.columns.tags
    Tags
    %ul.inline-list
      - @tags.each do |tag|
        %li
          = link_to tag.name, manager_tag_path(tag)
          (#{tag.galleries.length})

  .c
      

ish_manager-master/app/views/ish_manager/galleries/trash/all_photos.haml
- @photos.fresh.each do |ph|
  = image_tag ph.photo.url(:mini)

ish_manager-master/app/views/ish_manager/galleries/trash/index_short.haml
%h2
  = link_to 'Galleries', manager_galleries_path
  = link_to '[+]', new_manager_gallery_path

.as
  - @galleries.each do |g|
    .clear
    .a
      = link_to '[~]', edit_manager_gallery_path(g)
      = link_to g.name, manager_gallery_path(g.id)
      = link_to '[+]', new_photo_path( :galleryname => g.galleryname )
      = link_to '[++]', add_photos_path(g.id)
      .float-right= button_to '[x]', manager_gallery_path(g), :method => :delete

.clear
= paginate @galleries, :param_name => :galleries_page

ish_manager-master/app/views/ish_manager/galleries/trash/index_thumb.haml
.row
  .large-12.columns
    %h1 Manager Galleries List

    = paginate @galleries, :param_name => :galleries_page
    %ul
      - @galleries.each do |gallery|
        %li
          = link_to '[~]', edit_manager_gallery_path( gallery )
          = link_to gallery.name, manager_gallery_path( gallery )
          %br
          - gallery.photos.each_with_index do |photo, idx|
            - if idx < 8
              = image_tag photo.photo.url :thumb
    = paginate @galleries, :param_name => :galleries_page